package ui.paineis;

import gamesapi.GamesAPIController;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Rafael
 */
public class PaginatedList extends JPanel {

    private static GamesAPIController controller;
    
    public PaginatedList(GamesAPIController controller) {
        initComponents();
        
        PaginatedList.controller = controller;
        
        ArrayList<String> games = controller.getOwnedGamesNames();
        
        DefaultListModel<String> model = new DefaultListModel();
        for (Object game : games) {
            model.addElement((String) game);
        }
        JList list = new JList(model);
        list.setBackground(Color.GRAY);
        list.setCellRenderer(new ImagesListRenderer());
        
        JScrollPane scroll = new JScrollPane(list);
        scroll.setPreferredSize(new Dimension(800, 600));
        
        this.add(scroll);
    }
    
    public class ImagesListRenderer extends DefaultListCellRenderer{
        Font font = new Font("helvetica", Font.BOLD, 12);
        
        @Override
        public Component getListCellRendererComponent(
                JList list, Object value, int index, 
                boolean isSelected, boolean cellHasFocus){
            JLabel label = (JLabel) super.getListCellRendererComponent(
                    list, value, index, isSelected, cellHasFocus);
            label.setIcon(controller.getGameImagesMap().get((String) value));
            label.setHorizontalTextPosition(JLabel.RIGHT);
            label.setFont(font);
            return label;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
